# Generated by Django 4.2.30 on 2026-07-07 09:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(choices=[('action', 'Hành động'), ('comedy', 'Hài'), ('drama', 'Chính kịch'), ('horror', 'Kinh dị'), ('sci_fi', 'Khoa học viễn tưởng'), ('other', 'Khác')], db_index=True, max_length=50)),
                ('release_year', models.PositiveIntegerField(db_index=True)),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='app_movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_movie_ratings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='movierating',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_user_movie_rating'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_deleted', 'genre'], name='tb_movies_is_dele_a3335c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_deleted', 'release_year'], name='tb_movies_is_dele_325542_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_deleted', 'rating'], name='tb_movies_is_dele_face7b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['created_by', 'is_deleted'], name='tb_movies_created_9f48ff_idx'),
        ),
    ]
