# Generated by Django 4.2.30 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
